# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alfonso Alba
email: 
description: >- # this means to ignore newlines until "baseurl:"
  My public place in the internet.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.alfonsoalba.com" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true
# Build settings
markdown: kramdown
kramdown:
  parse_block_html: false
theme: jekyll-canvas-theme
plugins:
  - jekyll-feed
  - jekyll-responsive-image
  - jekyll-seo-tag


host: 0.0.0.0

permalink: /:year/:month/:day/:title:output_ext

tiles_count: 4

responsive_image:
  template: _includes/srcset_resize_fallback_template.html
  sizes:
    - width: 480
    - width: 600
    - width: 800
    - width: 1024
    - width: 1200
    - width: 1440

canvas:
  body_class: stretched
  default_share_image: '/assets/images/pattern2.png'
  date_format: "%b %-d, %Y"
  social_links:

twitter:
  username: aalbagarcia
facebook:
  app_id: 3551045798292698  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - artwork/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - docker-compose.yml
  - jekyll-website.code-workspace
